lista = list()
lista.append('digitar título')
lista.append('inserir imagem')
lista.append('alterar fonte')
print(f"Na primeira etapa foi removida a ação '{lista[-1]}'")
print(f"Na segunda etapa foi removida a ação '{lista[-2]}'")
lista.remove(lista[-1])
lista.remove(lista[-2])
print(f"Estado restante {lista}")